//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_Questionnaire_Control : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean NextQuestion
        {
            get
            {
                return SteamVR_Actions.questionnaire_Control_NextQuestion;
            }
        }
        
        public virtual SteamVR_Action_Boolean SelectAnswer
        {
            get
            {
                return SteamVR_Actions.questionnaire_Control_SelectAnswer;
            }
        }
        
        public virtual SteamVR_Action_Boolean InteractUI
        {
            get
            {
                return SteamVR_Actions.questionnaire_Control_InteractUI;
            }
        }
    }
}
